@startuml

:User: as User
:Admin: as Admin
:Patient: as Patient
:Doctor: as Doctor
:Non Authenticated User: as NonAuthenticatedUser

(I want to register new backoffice users via an out-of-band process, so that they can access the backoffice system with appropriate permissions) as (US_5.1.1)
(I want to reset my password if I forget it, so that I can regain access to the system securely) as (US_5.1.2)
(I want to register for the healthcare application, so that I can create a user profile and book appointments online.) as (US_5.1.3)
(I want to update my user profile, so that I can change my personal details and preferences) as (US_5.1.4)
(I want to delete my account and all associated data, so that I can exercise my right to be forgotten as per GDPR.) as (US_5.1.5)
(I want to log in to the system using my credentials, so that I can access the backoffice features according to my assigned role.) as (US_5.1.6)
(I want to log in to the healthcare system using my external IAM credentials, so that I can access my appointments, medical records, and other features securely) as (US_5.1.7)
(I want to create a new patient profile, so that I can register their personal details and medical history.) as (US_5.1.8)
(I want to edit an existing patient profile, so that I can update their information when needed.) as (US_5.1.9)
(I want to delete a patient profile, so that I can remove patients who are no longer under car) as (US_5.1.10)
(I want to list/search patient profiles by different attributes, so that I can view the details, edit, and remove patient profiles.) as (US_5.1.11)
(I want to create a new staff profile, so that I can add them to the hospital’s roster.) as (US_5.1.12)
(I want to edit a staff’s profile, so that I can update their information.) as (US_5.1.13)
(I want to deactivate a staff profile, so that I can remove them from the hospital’s active roster without losing their historical data.) as (US_5.1.14)
(I want to list/search staff profiles, so that I can see the details, edit, and remove staff profiles.) as (US_5.1.15)
(I want to request an operation, so that the Patient has access to the necessary healthcare.) as (US_5.1.16)
(I want to update an operation requisition, so that the Patient has access to the necessary healthcare) as (US_5.1.17)
(I want to remove an operation requisition, so that the healthcare activities are provided as necessary.) as (US_5.1.18)
(I want to list/search operation requisitions, so that I see the details, edit, and remove operation requisitions) as (US_5.1.19)
(I want to add new types of operations, so that I can reflect the available medical procedures in the system.) as (US_5.1.20)
(I want to edit existing operation types, so that I can update or correct information about the procedure) as (US_5.1.21)
(I want to remove obsolete or no longer performed operation types, so that the system stays current with hospital practices.) as (US_5.1.22)
(I want to list/search operation types, so that I can see the details, edit, and remove operation types) as (US_5.1.23)






Admin -> (US_5.1.1)
Admin -> (US_5.1.8)
Admin -> (US_5.1.9)
Admin -> (US_5.1.10)
Admin -> (US_5.1.11)
Admin -> (US_5.1.12)
Admin -> (US_5.1.13)
Admin -> (US_5.1.14)
Admin -> (US_5.1.15)
Admin -> (US_5.1.20)
Admin -> (US_5.1.21)
Admin -> (US_5.1.22)
Admin -> (US_5.1.23)

User -> (US_5.1.2)

Patient -> (US_5.1.3)
Patient -> (US_5.1.4)
Patient -> (US_5.1.5)
Patient -> (US_5.1.7)

NonAuthenticatedUser -> (US_5.1.6)

Doctor -> (US_5.1.16)
Doctor -> (US_5.1.17)
Doctor -> (US_5.1.18)
Doctor -> (US_5.1.19)




@enduml