@startuml
skinparam packageStyle rectangle
skinparam rectangle {
    BorderColor black
}

title Use Case Diagram - Healthcare System - Sprint 1

left to right direction

rectangle "System Actors" as actors {
    actor "Admin"
    actor "User"
    actor "Patient"
    actor "Doctor"
    actor "Non Authenticated User"
}

rectangle "Use Cases" as usecases {
    usecase "US_5.1.1: Register new backoffice users" as UC1
    usecase "US_5.1.2: Reset my password" as UC2
    usecase "US_5.1.3: Register for the healthcare application" as UC3
    usecase "US_5.1.4: Update user profile" as UC4
    usecase "US_5.1.5: Delete account and associated data (GDPR)" as UC5
    usecase "US_5.1.6: Log in to the system (backoffice)" as UC6
    usecase "US_5.1.7: Log in with external IAM credentials" as UC7
    usecase "US_5.1.8: Create a new patient profile" as UC8
    usecase "US_5.1.9: Edit an existing patient profile" as UC9
    usecase "US_5.1.10: Delete a patient profile" as UC10
    usecase "US_5.1.11: List/Search patient profiles" as UC11
    usecase "US_5.1.12: Create a new staff profile" as UC12
    usecase "US_5.1.13: Edit a staff profile" as UC13
    usecase "US_5.1.14: Deactivate a staff profile" as UC14
    usecase "US_5.1.15: List/Search staff profiles" as UC15
    usecase "US_5.1.16: Request an operation" as UC16
    usecase "US_5.1.17: Update an operation requisition" as UC17
    usecase "US_5.1.18: Remove an operation requisition" as UC18
    usecase "US_5.1.19: List/Search operation requisitions" as UC19
    usecase "US_5.1.20: Add new types of operations" as UC20
    usecase "US_5.1.21: Edit existing operation types" as UC21
    usecase "US_5.1.22: Remove obsolete operation types" as UC22
    usecase "US_5.1.23: List/Search operation types" as UC23

}

"Admin" --> UC1
"Admin" --> UC8
"Admin" --> UC9
"Admin" --> UC10
"Admin" --> UC11
"Admin" --> UC12
"Admin" --> UC13
"Admin" --> UC14
"Admin" --> UC15
"Admin" --> UC20
"Admin" --> UC21
"Admin" --> UC22
"Admin" --> UC23

"User" --> UC2

"Patient" --> UC3
"Patient" --> UC4
"Patient" --> UC5
"Patient" --> UC7

"Non Authenticated User" --> UC6

"Doctor" --> UC16
"Doctor" --> UC17
"Doctor" --> UC18
"Doctor" --> UC19

@enduml